package:
  name: sqlalchemy_frontier
  version: !!str 0.4.0

source:
  git_url: git@github.com:xiezhen/sqlalchemy_frontier.git
  git_tag: 0.4.0
    
build:
  number: 0

requirements:
  build:      
    - sqlalchemy
    - cx_oracle
    - frontier_client
    - python

