package:
  name: expat
  version: 2.2.0

source: 
  fn: expat-2.2.0.tar.bz2
  url: https://downloads.sourceforge.net/expat/expat-2.2.0.tar.bz2 
  md5: 2f47841c829facb346eb6e3fab5212e2

build:
  number: 0

about:
  home: http://expat.sourceforge.net/


