package:
  name: expat
  version: 2.0.1

source: 
  fn: expat-2.0.1-cms.tar.gz
  url: http://downloads.sourceforge.net/expat/expat-2.0.1.tar.gz
  md5: ee8b492592568805593f81f8cdf2a04c 

build:
  number: 0

about:
  home: http://expat.sourceforge.net/


