package:
  name: coral
  version: 2.4.1

source: 
  git_url: git@github.com:xiezhen/coralbuilder.git
  git_tag: v0.3

build:
  number: 0
  
requirements:
  build: 
    - boost
    - xerces-c
    - oraclesdk
    - oracleclientlite
    - frontier_client
    - python
  run:


about:
  home: https://twiki.cern.ch/twiki/bin/view/Persistency/Coral
  license: 


