package:
  name: docopt
  version: !!str 0.6.2

source:
  fn: docopt-0.6.2.tar.gz
  url: https://pypi.python.org/packages/source/d/docopt/docopt-0.6.2.tar.gz
  md5: 4bc74561b37fad5d3e7d037f82a4c3b1
  
# patches:
  # # List any patch files here
  # # - fix.patch

build:
  number: 2

requirements:
  build:
    - python
    - setuptools

  run:
    - python
 
test:
  # Python imports
  imports:
    - docopt

about:
  home: http://docopt.org
  license: MIT License
  summary: 'Pythonic argument parser, that will make you smile'

# See
# # http://docs.continuum.io/conda/build.html for
# # more information about meta.yaml
