package:
  name: frontier_client
  version: 2.8.19

source: 
  fn: frontier_client__2.8.19__src.tar.gz
  url: http://frontier.cern.ch/dist/frontier_client__2.8.19__src.tar.gz
  md5: 51acddfd70c1bd77c13d2ef03538638d

build:
  number: 0
  
requirements:
  build: 
    - expat
    - pacparser

  run:
    - expat

about:
  home: http://frontier.cern.ch/
  license: BSD license


