package:
  name: frontier_client
  version: 2.8.20

source: 
  fn: frontier_client__2.8.20__src.tar.gz
  url: http://frontier.cern.ch/dist/frontier_client__2.8.20__src.tar.gz
  md5: e2ea893b02eab539a0cf6a3812f4937c
build:
  number: 1
  
requirements:
  build: 
    - expat
    - pacparser
    - openssl

about:
  home: http://frontier.cern.ch/
  license: BSD license


