package:
  name: frontier_client
  version: 2.8.14

source: 
  fn: frontier_client__2.8.14__src.tar.gz
  url: http://frontier.cern.ch/dist/frontier_client__2.8.14__src.tar.gz
  md5: 8f18173f63312bf1dceae232f6bb39ec

build:
  number: 0
  
requirements:
  build: 
    - expat
    - pacparser

  run:
    - expat

about:
  home: http://frontier.cern.ch/
  license: BSD license


