package:
  name: root
  version: 5.99.05

source: 
  fn: root_v5.99.05.source.tar.gz
  url: https://root.cern.ch/download/root_v5.99.05.source.tar.gz
build:
  number: 1
  
requirements:
  build: 
    - jpeg
    - libtiff
    - libpng
    - pcre 
    - openssl 1.0.2h
    - zlib 1.2.8
    - python 2.7.12
    - xz
  run:


about:
  home: http://root.cern.ch
  license: LGPL 


