package:
  name: sqlplus
  version: 11.2.0.3.0__10.2.0.4.0

source: 
   fn: 20120309-instantclient-sqlplus-linux.x64-11.2.0.3.0.zip
   url: http://cmsrep.cern.ch/cmssw/oracle-mirror/20120309-instantclient-sqlplus-linux.x64-11.2.0.3.0.zip


build:
  number: 0

about:
  home: oracle
  license: oracle




