package:
  name: boost
  version: 1.51.0

source: 
  fn: boost-1.51.0.tar.bz2
  url: http://switch.dl.sourceforge.net/project/boost/boost/1.51.0/boost_1_51_0.tar.bz2

build:
  number: 0

about:
  home: http://www.boost.org/
  license: Boost-1.0

