package:
  name: pacparser
  version: 1.3.1

source: 
  fn: pacparser-1.3.1.tar.gz
  url: https://github.com/pacparser/pacparser/releases/download/1.3.1/pacparser-1.3.1.tar.gz

build:
  number: 2

about:
  home: http://pacparser.github.io
  license: GNU Lesser GPL

