package:
  name: pacparser
  version: 1.3.7

source: 
  git_url: https://github.com/pacparser/pacparser.git
  git_tag: 1.3.7

build:
  number: 0

about:
  home: http://pacparser.github.io
  license: GNU Lesser GPL

