package:
  name: pacparser
  version: 1.3.1

source: 
  fn: pacparser-1.3.1.tar.gz
  url: http://pacparser.googlecode.com/files/pacparser-1.3.1.tar.gz

build:
  number: 0

about:
  home: http://code.google.com/p/pacparser/
  license: GNU Lesser GPL

